### PR TITLE
fix/negative intervals

### LINKED ISSUE #1504: Migrating from 1.96 to 2.4 booking service issue
Updating from 2.4 I'm trying to get the booking service using the following basic code:

```
$services = $client->solutions()->bookingBusinesses()->byBookingBusinessId($businessId)->services()->get()->wait();
```
The request seem to work but the parsing in the model seem to produce an issue:
```
Uncaught Exception: Unknown or bad format (-PT15M) in C:\xampp74\htdocs\wp\wordpress\wp-content\plugins\CustomPlugin\vendor\microsoft\kiota-serialization-json\src\JsonParseNode.php:285 Stack trace: #0 C:\xampp74\htdocs\wp\wordpress\wp-content\plugins\CustomPlugin\vendor\microsoft\kiota-serialization-json\src\JsonParseNode.php(285): DateInterval->__construct('-PT15M') #1 C:\xampp74\htdocs\wp\wordpress\wp-content\plugins\CustomPlugin\vendor\microsoft\microsoft-graph\src\Generated\Models\BookingReminder.php(71): Microsoft\Kiota\Serialization\Json\JsonParseNode->getDateIntervalValue()
```

### PR DESCRIPTION
**Pull request by SilasKenneth**
- **Make sure negative date periods are correctly handled.**

Closes https://github.com/microsoftgraph/msgraph-sdk-php/issues/1504

Depends on: https://github.com/microsoft/kiota-abstractions-php/pull/144

### CODE REVIEW

File: src/TextSerializationWriter.php [hunk 1]
```diff
@@ -186,9 +186,15 @@ public function writeTimeValue(?string $key, ?Time $value): void
      */
     public function writeDateIntervalValue(?string $key, ?DateInterval $value): void
     {
-        if ($value) {
-            $valueString = "P{$value->y}Y{$value->y}M{$value->d}DT{$value->h}H{$value->i}M{$value->s}S";
-            $this->writeStringValue($key, $valueString);
+        if ($value !== null){
```
Comment (baywet) [inline src/TextSerializationWriter.php:193]: instead of duplicating this logic all over the place, could we add a toString (or different name that makes more sense) in the abstractions?

File: src/TextParseNode.php [hunk 2]
```diff
@@ -146,7 +146,18 @@ public function getDateTimeValue(): ?DateTime
      */
     public function getDateIntervalValue(): ?DateInterval
     {
-        return new DateInterval($this->content);
+        $originalValue = $this->content;
```
Comment (baywet) [inline src/TextParseNode.php]: same comment with a parse/from string static method

**Review by baywet — CHANGES_REQUESTED** [review]

File: src/TextSerializationWriter.php (hunk 1 above)
Comment (SilasKenneth) [reply src/TextSerializationWriter.php:193]: Please check https://github.com/microsoft/kiota-abstractions-php/pull/144

**Comment by SilasKenneth** [comment]
Converting this to draft to wait for https://github.com/microsoft/kiota-abstractions-php/pull/144

**Review by baywet — APPROVED** [review]
